### ISSUE TITLE
1 1 7,14,21,L * * errors out (i.e. can't mix "L" with day digits)

### ISSUE THREAD

**Issue by mister-average** [taichino/croniter#127]
```
base = datetime(2018, 10, 1)
itr = croniter.croniter('1 1 7,14,21,L * *', base)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/croniter/croniter.py", line 92, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format)
  File "/xxx/croniter/croniter.py", line 550, in expand
    res.sort()
TypeError: '<' not supported between instances of 'int' and 'str'

```
Can be fixed by going to around line 550/558 in croniter.py and replacing:
```
            res.sort()
```
with:
```
            if 'l' in res:
                res[res.index('l')] = 99

            res.sort()

            if 99 in res:
                res[res.index(99)] = 'l'
```

**Comment by kiorky** [comment]
[0.3.32](https://pypi.org/project/croniter/) is out !
