### ISSUE TITLE
A crafted cron expression can cause get_next() to raise a TypeError

### ISSUE THREAD

**Issue by cuu508** [taichino/croniter#156]
I'm running this:

```
from datetime import datetime
from croniter import croniter

start = datetime(2022, 1, 1)
pattern = "* * * * *,0"
it = croniter(pattern, start)
it.get_next(datetime)
```

and getting this traceback:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    it.get_next(datetime)
  File "/home/user/venvs/croniter-fuzzing/lib/python3.8/site-packages/croniter/croniter.py", line 129, in get_next
    return self._get_next(ret_type or self._ret_type, is_prev=False)
  File "/home/user/venvs/croniter-fuzzing/lib/python3.8/site-packages/croniter/croniter.py", line 208, in _get_next
    result = self._calc(self.cur, expanded,
  File "/home/user/venvs/croniter-fuzzing/lib/python3.8/site-packages/croniter/croniter.py", line 456, in _calc
    (changed, dst) = proc(dst)
  File "/home/user/venvs/croniter-fuzzing/lib/python3.8/site-packages/croniter/croniter.py", line 349, in proc_day_of_week
    diff_day_of_week = nearest_diff_method(
  File "/home/user/venvs/croniter-fuzzing/lib/python3.8/site-packages/croniter/croniter.py", line 489, in _get_next_nearest_diff
    if d >= x:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

The constructor accepts the cron expression, but then `get_next()` throws an exception. 
From the consumer POV, ideally the constructor would reject the nonsensical cron expression. If that's not feasible, get_next would raise one of the croniter's custom exceptions instead of TypeError.

**Comment by kiorky** [comment]
Nope, for the constructor, it will not raises as it was not how croniter was designed.

However, it should certainly raises something whenever cron needs to validate, its the purpose of `expand` method and it's consumers like the `is_valid` method that you can use for those purposes.

I'll handle this case to fix the bug.

**Comment by kiorky** [comment]
1.0.6 is out
