### ISSUE TITLE
February 29

### ISSUE THREAD

**Issue by magnushiie** [taichino/croniter#55]
The following expression gives an exception with 0.3.11:

``` python
from croniter import croniter
from datetime import datetime
croniter("0 9 29 2 *", datetime(2016, 2, 29, 9, 0)).get_next(datetime)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\croniter\croniter.py", line 141, in get_next
    return self._get_next(ret_type, is_prev=False)
  File "C:\Python27\lib\site-packages\croniter\croniter.py", line 224, in _get_next
    result = self._calc(self.cur, expanded, is_prev)
  File "C:\Python27\lib\site-packages\croniter\croniter.py", line 362, in _calc
    raise Exception("failed to find prev date")
Exception: failed to find prev date
```

The same in 0.3.8 worked, gave `datetime.datetime(2020, 2, 29, 9, 0)` as the answer.

**Comment by kiorky** [comment]
Msg is fixed

```
>>> croniter("0 9 29 2 *", datetime(2016, 2, 29, 9, 0)).get_next(datetime)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kiorky/projects/mc/croniter/src/croniter/croniter.py", line 170, in get_next
    return self._get_next(ret_type or self._ret_type, is_prev=False)
  File "/home/kiorky/projects/mc/croniter/src/croniter/croniter.py", line 256, in _get_next
    result = self._calc(self.cur, expanded, is_prev)
  File "/home/kiorky/projects/mc/croniter/src/croniter/croniter.py", line 396, in _calc
    raise CroniterBadDateError("failed to find next date")
croniter.croniter.CroniterBadDateError: failed to find next date
```

**Comment by magnushiie** [comment]
I don't think an exception is a valid solution here, no matter what the message is. Or is it that croniter does not support leap years anymore?
